const studentsData = [
  {
    id: 1,
    name: 'abc',
    ticketNumber: 'A123',
    ticketTopic: 'React',
    examGrade: 4,
    ratingGrade: 5,
    comments: 'Good work',
  },
  {
    id: 2,
    name: 'def',
    ticketNumber: 'B456',
    ticketTopic: 'Angular',
    examGrade: 3,
    ratingGrade: 4,
    comments: 'Needs improvement',
  },
  {
    id: 3,
    name: 'ghi',
    ticketNumber: 'C789',
    ticketTopic: 'Vue',
    examGrade: 5,
    ratingGrade: 4,
    comments: 'Well done',
  },
  {
    id: 4,
    name: 'jkl',
    ticketNumber: 'D012',
    ticketTopic: 'React',
    examGrade: 2,
    ratingGrade: 3,
    comments: 'Could do better',
  },
  {
    id: 5,
    name: 'mno',
    ticketNumber: 'E345',
    ticketTopic: 'Angular',
    examGrade: 4,
    ratingGrade: 5,
    comments: 'Excellent work',
  },
  {
    id: 6,
    name: 'pqr',
    ticketNumber: 'F678',
    ticketTopic: 'Vue',
    examGrade: 3,
    ratingGrade: 4,
    comments: 'Good effort',
  },
  {
    id: 7,
    name: 'stu',
    ticketNumber: 'G901',
    ticketTopic: 'React',
    examGrade: 5,
    ratingGrade: 3,
    comments: 'Impressive work',
  },
  {
    id: 8,
    name: 'vwx',
    ticketNumber: 'H234',
    ticketTopic: 'Angular',
    examGrade: 4,
    ratingGrade: 4,
    comments: 'Well done',
  },
  {
    id: 9,
    name: 'yz1',
    ticketNumber: 'I567',
    ticketTopic: 'Vue',
    examGrade: 3,
    ratingGrade: 2,
    comments: 'Needs improvement',
  },
  {
    id: 10,
    name: '234',
    ticketNumber: 'J890',
    ticketTopic: 'React',
    examGrade: 5,
    ratingGrade: 4,
    comments: 'Good job',
  },
  {
    id: 11,
    name: '567',
    ticketNumber: 'K123',
    ticketTopic: 'Angular',
    examGrade: 2,
    ratingGrade: 3,
    comments: 'Could do better',
  },
  {
    id: 12,
    name: '890',
    ticketNumber: 'L456',
    ticketTopic: 'Vue',
    examGrade: 4,
    ratingGrade: 5,
    comments: 'Excellent work',
  },
  {
    id: 13,
    name: 'abc1',
    ticketNumber: 'M789',
    ticketTopic: 'React',
    examGrade: 3,
    ratingGrade: 4,
    comments: 'Good effort',
  },
  {
    id: 14,
    name: 'def1',
    ticketNumber: 'N012',
    ticketTopic: 'Angular',
    examGrade: 5,
    ratingGrade: 3,
    comments: 'Impressive work',
  },
  {
    id: 15,
    name: 'ghi1',
    ticketNumber: 'O345',
    ticketTopic: 'Vue',
    examGrade: 4,
    ratingGrade: 4,
    comments: 'Well done',
  },
];

export default studentsData;
